// <auto-generated />
namespace Eregister.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NoSeperateContextallInOneIdentityContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoSeperateContextallInOneIdentityContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201712110117532_NoSeperateContextallInOneIdentityContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
